language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
before_install:
  - export BUILD_DIR=$PWD
  - sudo apt-get install -y maven
  - cd /tmp/
  - git clone https://github.com/antlr/antlr4.git
  - cd antlr4 ; git checkout 4.7.2;
  - export MAVEN_OPTS="-Xmx1G"   # don't forget this on linux
  - mvn clean                    # must be separate, not part of install/compile
  - mvn -DskipTests install
  - mvn install -DskipTests=true   #
  - alias antlr4='java -Xmx500M -cp "/tmp/antlr4/tool/target/antlr4-4.7.2-complete.jar:$CLASSPATH" org.antlr.v4.Tool
install:
  - cd $BUILD_DIR
  - pip3 install antlr4-python3-runtime===4.7.2 matplotlib numpy 
# command to run tests
script:
  - make all
  - python3 test.py
