dist: bionic
language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
  - sudo apt-get update
  - apt-cache policy antlr4 # Check what is latest
  - sudo apt-get install -y antlr4=4.7.2-1~18.04
install:
  - pip3 install antlr4-python3-runtime===4.7.2 matplotlib numpy 
# command to run tests
script:
  - make all
  - python3 test.py
