name: "Benchmark: Python libraries"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Benchmark
        run: |
            pip install -r scripts/python_benchmark/requirements.txt
            python3 scripts/python_benchmark/benchmark.py

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: doc/JOSS/py.PNG
