name: "Benchmark: Python libraries"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Benchmark
        run: |
            pip install -r scripts/python_benchmark/requirements.txt
            python3 scripts/python_benchmark/benchmark.py

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: py_benchmark
          path: doc/JOSS/py.PNG
