name: "Test: C/C++"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: python deps
      run: python3 -m pip install -r reqs/requirements.txt
    - name: make test
      run: make test
