name: "Test: C/C++/Python"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install -r reqs/requirements.txt
        make all
    - name: make test
      run: make test
  
  build_win:

    runs-on: windows-2022

    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-22.04
        update: 'true'
        additional-packages:
          python3-dev
          bison
          flex
          python3-pip
          build-essential 
          libssl-dev 
          libffi-dev
          python3.10-venv
    
    - uses: actions/checkout@v2
    - name: prep for pip
      shell: wsl-bash {0}
      run: |
        #python3 -m venv env
        #source env/bin/activate    
        unset DISPLAY 
    - name: pip installs
      shell: wsl-bash {0}
      run: |
        echo "pip"source env/bin/activate    
        #unset DISPLAY
        #python3 -m pip  -vvv --no-cache-dir install --upgrade pip
        # python3 -m pip install -r reqs/requirements.txt
        #echo "Cppyy"
        #python3 -m pip  -vvv --no-cache-dir  install cppyy --user
        # echo "pytest"
        #python3 -m pip  -vvv --no-cache-dir  install pytest --user
        
    - name: test
      shell: wsl-bash {0}
      run: |
        make all
        ./build/dice d100
