name: "Test: Javascript"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: python deps
      run: python3 -m pip install -r reqs/requirements.txt
    - name: javascript prerequisites
      run: |
        sudo apt install nodejs 
        wget -c http://archive.ubuntu.com/ubuntu/pool/universe/e/emscripten/emscripten_1.22.1-1build1_amd64.deb
        sudo apt install ./emscripten_1.22.1-1build1_amd64.deb
    - name: make js
      run: |
        make all
        emcc -v
        make js
        ./src/js/a.out.js 1d20
        
