name: "Manual: Memory Leaks"

on:
  workflow_dispatch

jobs:
  valgrind:
    runs-on: ubuntu-latest
    name: Memory Leak detection 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lib Install
        run: |
            make all DEBUG=1
 
      - name: Run Valgrind 
        run: valgrind ./build/dice d20
